Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox"

  config.vm.box = "egavm"

  config.vm.define "egavm" do |v|
  end

  config.vm.network "forwarded_port", guest: 3000, host: 30080

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # VirtualBox
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.name = "egavm"
    v.memory = 4096
    v.cpus = 4
  end

end
