# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "parallels"

  config.vm.box = "box-cutter/ubuntu1404-desktop"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 3000, host: 30080

  config.vm.synced_folder "../prepare", "/prepare", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Parallels 
  config.vm.provider "parallels" do |v|
    v.memory = 4096
    v.cpus = 4
  end

end
