# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox"
  
  config.vm.box = "box-cutter/ubuntu1404-desktop"

  config.vm.define "egavm-v" do |v|
  end

  config.vm.network "forwarded_port", guest: 3000, host: 30080

  config.vm.synced_folder "upload", "/home/vagrant/ega/upload", owner: "vagrant", group: "vagrant", create: true
  config.vm.synced_folder "../prepare", "/prepare", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # VirtualBox
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.name = "egavm-v"
    v.memory = 4096
    v.cpus = 4
  end

end
