# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox"
  
  config.vm.box = "mytrusty"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 3000, host: 30080

  config.vm.synced_folder "../../prepare", "/prepare", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # VirtualBox
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = 2048
    v.cpus = 2
    v.name = "egavm-build"

    v.customize ["setextradata", "global", "GUI/MaxGuestResolution", "any"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end

end
